#include "ui/NlPromptBar.h"

#include <QHBoxLayout>
#include <QLabel>
#include <QLineEdit>
#include <QPushButton>

#include "ai/ClaudeSqlGenerator.h"
#include "ai/LocalSqlGenerator.h"

namespace ds {

NlPromptBar::NlPromptBar(QWidget* parent) : QWidget(parent) {
  input_ = new QLineEdit(this);
  input_->setPlaceholderText(
      QStringLiteral("Ask in plain English — “top 10 customers by revenue "
                     "last month”"));
  input_->setClearButtonEnabled(true);

  askButton_ = new QPushButton(QStringLiteral("Generate SQL"), this);

  // Doubles as the current-provider readout and the way into its settings.
  providerButton_ = new QPushButton(this);
  providerButton_->setFlat(true);
  providerButton_->setCursor(Qt::PointingHandCursor);
  providerButton_->setStyleSheet(
      QStringLiteral("color: gray; text-align: right;"));
  connect(providerButton_, &QPushButton::clicked, this,
          &NlPromptBar::configureRequested);

  status_ = new QLabel(this);
  status_->setStyleSheet(QStringLiteral("color: gray;"));

  auto* layout = new QHBoxLayout(this);
  layout->setContentsMargins(6, 4, 6, 4);
  layout->addWidget(new QLabel(QStringLiteral("✨"), this));
  layout->addWidget(input_, 1);
  layout->addWidget(providerButton_);
  layout->addWidget(askButton_);
  layout->addWidget(status_);

  connect(input_, &QLineEdit::returnPressed, this, &NlPromptBar::submit);
  connect(askButton_, &QPushButton::clicked, this, &NlPromptBar::submit);

  reloadSettings();
}

void NlPromptBar::reloadSettings() {
  settings_ = AiSettings::load();

  delete generator_;
  generator_ = nullptr;

  switch (settings_.provider) {
    case AiProvider::Local:
      generator_ = new LocalSqlGenerator(settings_, this);
      break;
    case AiProvider::Claude:
      generator_ = new ClaudeSqlGenerator(settings_, this);
      break;
    case AiProvider::None:
      break;
  }

  providerButton_->setText(settings_.provider == AiProvider::None
                               ? QStringLiteral("set up…")
                               : settings_.label());
  providerButton_->setToolTip(
      settings_.provider == AiProvider::Local
          ? QStringLiteral("Generating with a local model at %1 — nothing "
                           "leaves this machine.").arg(settings_.localBaseUrl)
          : QStringLiteral("Click to change where SQL is generated."));

  const bool ready = generator_ != nullptr;
  input_->setEnabled(ready);
  askButton_->setEnabled(ready);
  input_->setPlaceholderText(
      ready ? QStringLiteral("Ask in plain English — “top 10 customers by "
                             "revenue last month”")
            : QStringLiteral("Set up a local model or the Claude API to ask "
                             "questions in English"));

  if (!generator_) {
    status_->clear();
    return;
  }

  connect(generator_, &SqlGenerator::succeeded, this,
          [this](const NlSqlResult& result) {
            setBusy(false);

            QStringList notes;
            if (!result.explanation.isEmpty()) notes << result.explanation;
            if (!result.caveats.isEmpty()) {
              notes << QStringLiteral("Assumed: ") + result.caveats;
            }
            if (result.destructive) {
              notes << QStringLiteral("⚠ This statement modifies data — read "
                                      "it before running.");
            }
            notes << QStringLiteral("(generated by %1)")
                         .arg(result.providerLabel);
            const QString explanation = notes.join(QStringLiteral("  "));

            status_->setText(result.destructive
                                 ? QStringLiteral("⚠ writes data")
                                 : QStringLiteral("✓ ready to review"));
            status_->setStyleSheet(result.destructive
                                       ? QStringLiteral("color: #c98a20;")
                                       : QStringLiteral("color: #2d8a4e;"));
            emit sqlGenerated(result.sql, explanation);
            emit statusMessage(explanation);
          });

  connect(generator_, &SqlGenerator::failed, this,
          [this](const QString& message) {
            setBusy(false);
            status_->setText(QStringLiteral("✗"));
            status_->setStyleSheet(QStringLiteral("color: #d05050;"));
            status_->setToolTip(message);
            emit statusMessage(message);
          });
}

void NlPromptBar::focusInput() {
  input_->setFocus();
  input_->selectAll();
}

void NlPromptBar::setBusy(bool busy) {
  input_->setEnabled(!busy);
  askButton_->setEnabled(!busy);
  askButton_->setText(busy ? QStringLiteral("Thinking…")
                           : QStringLiteral("Generate SQL"));
}

void NlPromptBar::submit() {
  const QString question = input_->text().trimmed();
  if (question.isEmpty()) return;
  if (!generator_) {
    emit configureRequested();
    return;
  }

  setBusy(true);
  status_->clear();
  status_->setToolTip(QString());
  emit statusMessage(
      settings_.provider == AiProvider::Local
          ? QStringLiteral("Asking %1 locally — nothing leaves this machine.")
                .arg(settings_.localModel)
          : QStringLiteral("Asking Claude — the schema is sent, no row data "
                           "leaves this machine."));
  generator_->ask(question, schema_, dialect_);
}

}  // namespace ds
